import Head from 'next/head';
import { Fragment } from 'react';
import NavBar from '../components/NavBar/NavBar';
import Card from "../components/Card/Card";
import axios from 'axios';
import IndexProps from './Index.props';
import CardProps from '../components/Card/Card.props';

export default function Home({allCard, itemAll}:IndexProps): JSX.Element {
  
  let num = 0;
  const get = (title:string) => {
    if (num < itemAll.length)
    {
      if(itemAll[num].title == title){
        num++;
        return true;
      }
    } 
  };



  return (
    <Fragment>
      <Head>
         <title>Sneakers</title>
         <meta name="description" content="Generated by create next app" />
      </Head>

        <NavBar/>
        
        <div className="row modal-open">
          {
            
             allCard.map((obj:CardProps,) => {return (get(obj.title) ? <Card title = {obj.title} src = {obj.src} price = {obj.price} currency= {obj.currency} basked = {obj.basked} getLove={true}/> : <Card title = {obj.title} src = {obj.src} price = {obj.price} currency= {obj.currency} basked = {obj.basked} getLove={false}/>);})
             
          }
          
        </div>
    </Fragment>
  );
}

Home.getInitialProps = async () => {
    
    const card = await axios.get('http://localhost:5000/posts');
    const allCard = card.data;
    
    const item = await axios.get('http://localhost:5000/carditem');
    const itemAll = item.data;

    return { allCard , itemAll };
};



